use std::fs;
use std::path::PathBuf;
use crate::param::SystemConfig;

/// Generate main.rs content based on SystemConfig
pub fn create_main_rs_content(system: &SystemConfig) -> String {
    let mut content = String::new();
    
    // Generate header section
    content.push_str(&generate_header_section());
    
    // Generate import section
    content.push_str(&generate_import_section(system));

    // Generate main function
    content.push_str(&generate_main_function(system));
    
    content
}

/// Generate header section for main.rs
pub fn generate_header_section() -> String {
    let mut header = String::new();
    
    header.push_str("//SPDX-License-Identifier: MIT\n");
    header.push_str("//SPDX-FileCopyrightText: 2025 Ryosuke Yamamoto <yama05rymy@gmail.com>\n\n");
    header.push_str("//! Virtual machine configuration generated by VPG\n");
    header.push_str("#![no_main]\n");
    header.push_str("#![no_std]\n");
    header.push_str("#![feature(used_with_arg)]\n\n");
    header.push_str("pub mod setup;\n");
    
    header
}

/// Generate import section for main.rs
pub fn generate_import_section(system: &SystemConfig) -> String {
    let mut imports = String::new();
    
    // Add VM module declarations
    for (vm_name, _) in &system.vms {
        // Extract VM type from name (e.g., vm_linux -> linux)
        let vm_type = vm_name.strip_prefix("vm_").unwrap_or(vm_name);
        imports.push_str(&format!("pub mod {};\n", vm_type));
    }
    imports.push_str("\n");
    
    imports.push_str("extern crate violet;\n");
    imports.push_str("use violet::kernel::syscall::vsi::create_task;\n\n");
    
    // Add VM boot function imports
    for (vm_name, vm) in &system.vms {
        let vm_type = vm_name.strip_prefix("vm_").unwrap_or(vm_name);
        imports.push_str(&format!("use crate::{}::boot_{};\n", vm_type, vm_type));
    }
    imports.push_str("\n");
    
    imports
}

/// Generate main function that starts all VMs
pub fn generate_main_function(system: &SystemConfig) -> String {
    let mut content = String::new();
    
    content.push_str("pub fn main() {\n");
    
    // Generate VM creation tasks
    for (vm_index, (vm_name, vm)) in system.vms.iter().enumerate() {
        let boot_core = if !vm.cpus.pcpu_mapping.is_empty() {
            vm.cpus.pcpu_mapping[0]
        } else {
            vm_index as u64
        };
        
        let vm_type = vm_name.strip_prefix("vm_").unwrap_or(vm_name);
        
        content.push_str(&format!(
            "    // Boot {} ({}) on core {}\n",
            vm_name, vm.os, boot_core
        ));
        content.push_str(&format!(
            "    create_task({}, boot_{}, {});\n",
            vm_index + 1, vm_type, boot_core
        ));
    }
    
    content.push_str("}\n");
    content
}

/// Generate main.rs file at the specified path
pub fn generate_main_rs(path: &String, system: &SystemConfig) {
    let main_rs_content = create_main_rs_content(system);
    let main_path = PathBuf::from(path).join("src").join(make_main_rs());
    fs::write(&main_path, main_rs_content).unwrap();
}

/// File extension utility to avoid string literal parsing issues
fn make_main_rs() -> String { 
    format!("main.{}", "rs") 
}
